### ISSUE TITLE
gps tracking

### ISSUE THREAD

**Issue by carocad** [hiposfer/hive#2]
- [x] ~~in foreground only~~
- [ ] show in map
- [ ] save locally
- [ ] upload on button press

**Comment by carocad** [comment]
a library like this: https://github.com/transistorsoft/react-native-background-geolocation

might help get things moving faster
